import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState, useRef } from "react";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleEmailChange = (e) => {
    console.log(e.target.value);
    setEmail(e.target.value);
  };

  const handlePasswordChange = (e) => {
    setPassword(e.target.value);
  };

  const handleSubmit = async (e) => {
    e.preventDefault(); //Cancel the normal form submit behavior so that I can inspect the data.
    const { data, error } = await supabaseClient.auth.signInWithPassword({
      email: email,
      password: password,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>To-Do</a> App
        </h1>

        <form className="form-control" onSubmit={handleSubmit}>
          <label htmlFor="email" className="label">
            Email
          </label>
          <input
            className="input"
            value={email}
            onChange={handleEmailChange}
            type="text"
            name="email"
            id="email"
          />
          <label htmlFor="password" className="label">
            Password
          </label>
          <input
            className="input"
            value={password}
            onChange={handlePasswordChange}
            type="text"
            name="fullname"
            id="fullname"
          />
          <br />
          <button className="btn btn-primary" type="submit">
            Login
          </button>
          <br />
        </form>
      </main>

      <footer className={styles.footer}>Powered by Hein Htet Aung</footer>
    </div>
  );
}
